package com.beyond.cloud.svc.storage.mapper;

import com.beyond.cloud.storage.domain.entity.Storage;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface StorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_storage
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_storage
     *
     * @mbg.generated
     */
    int insert(Storage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_storage
     *
     * @mbg.generated
     */
    int insertSelective(Storage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_storage
     *
     * @mbg.generated
     */
    Storage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Storage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Storage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyVersioned(Storage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_storage
     *
     * @mbg.generated
     */
    int updateVersionedSelective(Storage record);
}