package com.beyond.cloud.svc.storage.mapper.base;

import com.beyond.cloud.storage.domain.entity.Storage;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface StorageBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_tbl
     *
     * @mbg.generated Thu Jul 30 11:14:43 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_tbl
     *
     * @mbg.generated Thu Jul 30 11:14:43 CST 2020
     */
    int insert(Storage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_tbl
     *
     * @mbg.generated Thu Jul 30 11:14:43 CST 2020
     */
    int insertSelective(Storage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_tbl
     *
     * @mbg.generated Thu Jul 30 11:14:43 CST 2020
     */
    Storage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_tbl
     *
     * @mbg.generated Thu Jul 30 11:14:43 CST 2020
     */
    int updateByPrimaryKeySelective(Storage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_tbl
     *
     * @mbg.generated Thu Jul 30 11:14:43 CST 2020
     */
    int updateByPrimaryKey(Storage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_tbl
     *
     * @mbg.generated Thu Jul 30 11:14:43 CST 2020
     */
    int updateByPrimaryKeyVersioned(Storage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_tbl
     *
     * @mbg.generated Thu Jul 30 11:14:43 CST 2020
     */
    int updateVersionedSelective(Storage record);
}