package com.beyond.cloud.account.domain.entity;

import java.io.Serializable;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table bc_account
 */
public class Account implements Serializable {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_account.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     * 用户Id
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_account.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * Database Column Remarks:
     * 余额(单位:分)
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_account.balance
     *
     * @mbg.generated
     */
    private Integer balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_account.is_disabled
     *
     * @mbg.generated
     */
    private Boolean disabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bc_account
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_account.id
     *
     * @return the value of bc_account.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_account.id
     *
     * @param id the value for bc_account.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_account.user_id
     *
     * @return the value of bc_account.user_id
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_account.user_id
     *
     * @param userId the value for bc_account.user_id
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_account.balance
     *
     * @return the value of bc_account.balance
     * @mbg.generated
     */
    public Integer getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_account.balance
     *
     * @param balance the value for bc_account.balance
     * @mbg.generated
     */
    public void setBalance(Integer balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_account.is_disabled
     *
     * @return the value of bc_account.is_disabled
     * @mbg.generated
     */
    public Boolean getDisabled() {
        return disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_account.is_disabled
     *
     * @param disabled the value for bc_account.is_disabled
     * @mbg.generated
     */
    public void setDisabled(Boolean disabled) {
        this.disabled = disabled;
    }

}
