package com.beyond.cloud.account.domain.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table bc_pay_record
 */
public class PayRecord implements Serializable {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_pay_record.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_pay_record.account_id
     *
     * @mbg.generated
     */
    private Integer accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_pay_record.pay_money
     *
     * @mbg.generated
     */
    private Integer payMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_pay_record.pay_time
     *
     * @mbg.generated
     */
    private Date payTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bc_pay_record
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_pay_record.id
     *
     * @return the value of bc_pay_record.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_pay_record.id
     *
     * @param id the value for bc_pay_record.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_pay_record.account_id
     *
     * @return the value of bc_pay_record.account_id
     * @mbg.generated
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_pay_record.account_id
     *
     * @param accountId the value for bc_pay_record.account_id
     * @mbg.generated
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_pay_record.pay_money
     *
     * @return the value of bc_pay_record.pay_money
     * @mbg.generated
     */
    public Integer getPayMoney() {
        return payMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_pay_record.pay_money
     *
     * @param payMoney the value for bc_pay_record.pay_money
     * @mbg.generated
     */
    public void setPayMoney(Integer payMoney) {
        this.payMoney = payMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_pay_record.pay_time
     *
     * @return the value of bc_pay_record.pay_time
     * @mbg.generated
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_pay_record.pay_time
     *
     * @param payTime the value for bc_pay_record.pay_time
     * @mbg.generated
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

}
