package com.beyond.cloud.order.domain.entity;

import java.io.Serializable;

public class Order implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_tbl.id
     *
     * @mbg.generated Thu Jul 30 11:10:10 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_tbl.user_id
     *
     * @mbg.generated Thu Jul 30 11:10:10 CST 2020
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_tbl.commodity_code
     *
     * @mbg.generated Thu Jul 30 11:10:10 CST 2020
     */
    private String commodityCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_tbl.count
     *
     * @mbg.generated Thu Jul 30 11:10:10 CST 2020
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_tbl.money
     *
     * @mbg.generated Thu Jul 30 11:10:10 CST 2020
     */
    private Integer money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_tbl
     *
     * @mbg.generated Thu Jul 30 11:10:10 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_tbl.id
     *
     * @return the value of order_tbl.id
     *
     * @mbg.generated Thu Jul 30 11:10:10 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_tbl.id
     *
     * @param id the value for order_tbl.id
     *
     * @mbg.generated Thu Jul 30 11:10:10 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_tbl.user_id
     *
     * @return the value of order_tbl.user_id
     *
     * @mbg.generated Thu Jul 30 11:10:10 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_tbl.user_id
     *
     * @param userId the value for order_tbl.user_id
     *
     * @mbg.generated Thu Jul 30 11:10:10 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_tbl.commodity_code
     *
     * @return the value of order_tbl.commodity_code
     *
     * @mbg.generated Thu Jul 30 11:10:10 CST 2020
     */
    public String getCommodityCode() {
        return commodityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_tbl.commodity_code
     *
     * @param commodityCode the value for order_tbl.commodity_code
     *
     * @mbg.generated Thu Jul 30 11:10:10 CST 2020
     */
    public void setCommodityCode(String commodityCode) {
        this.commodityCode = commodityCode == null ? null : commodityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_tbl.count
     *
     * @return the value of order_tbl.count
     *
     * @mbg.generated Thu Jul 30 11:10:10 CST 2020
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_tbl.count
     *
     * @param count the value for order_tbl.count
     *
     * @mbg.generated Thu Jul 30 11:10:10 CST 2020
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_tbl.money
     *
     * @return the value of order_tbl.money
     *
     * @mbg.generated Thu Jul 30 11:10:10 CST 2020
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_tbl.money
     *
     * @param money the value for order_tbl.money
     *
     * @mbg.generated Thu Jul 30 11:10:10 CST 2020
     */
    public void setMoney(Integer money) {
        this.money = money;
    }
}